class TokenType:
    OPENPARENTHESIS = 1
    CLOSEPARENTHESIS = 2
    KEYWORD = 3
    NUMERICLITERAL = 4
    STRINGLITERAL = 5
    IDENTIFIER = 6
    ARITHMETICOPERATOR = 7
    RELATIONALOPERATOR = 8
    ASSIGNMENT = 9
    SPECIALCHARACTER = 10
    ENDOFLINE = 11
    ENDOFFILE = 12
    